//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        public Bancos()
        {
            this.Cotizaciones = new HashSet<Cotizaciones>();
        }
    
        public int IdBanco { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
    }
}
