//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Credito = new HashSet<Credito>();
            this.Reserva = new HashSet<Reserva>();
            this.Seguro = new HashSet<Seguro>();
            this.Cotizaciones = new HashSet<Cotizaciones>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<Credito> Credito { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Seguro> Seguro { get; set; }
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
    }
}
