//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public int IdCotizacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdAseguradora { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Aseguradoras Aseguradoras { get; set; }
        public virtual Bancos Bancos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
