//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        public int Id_Credito { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> Plazo { get; set; }
        public Nullable<decimal> Tasa_Interes { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
