//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha_Reserva { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
