//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        public int Id_Seguro { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Cobertura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
