//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.Reserva = new HashSet<Reserva>();
            this.Seguro = new HashSet<Seguro>();
            this.Cotizaciones = new HashSet<Cotizaciones>();
        }
    
        public int Id_Vehiculo { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Modelo { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual ICollection<Seguro> Seguro { get; set; }
        public virtual ICollection<Cotizaciones> Cotizaciones { get; set; }
    }
}
